# Generated by Django 3.2 on 2022-05-03 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='name')),
                ('phone_number', models.CharField(max_length=11, verbose_name='phone number')),
                ('website', models.CharField(blank=True, max_length=50, null=True, verbose_name='website')),
                ('message', models.TextField(verbose_name='message')),
                ('read', models.BooleanField(default=False, verbose_name='read or unread')),
                ('active', models.BooleanField(default=False, verbose_name='active or deactive')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'ordering': ('-created',),
            },
        ),
    ]
