# Generated by Django 3.2 on 2022-05-29 20:00

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_us', ckeditor.fields.RichTextField(verbose_name='about us')),
                ('contact_us', ckeditor.fields.RichTextField(verbose_name='contact us')),
            ],
        ),
    ]
