# Generated by Django 3.2 on 2022-06-06 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sitesetting'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesetting',
            options={'verbose_name': 'Site setting', 'verbose_name_plural': 'Site settings'},
        ),
    ]
