# Generated by Django 3.2 on 2022-05-10 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='title')),
                ('type', models.CharField(choices=[('alarm', 'آلارم'), ('dropbox', 'دراپ باکس'), ('reply', 'بازخورد'), ('ship', 'حمل و نقل'), ('heart-filled', 'علاقه مندی'), ('thunder', 'رعد و برق'), ('offer', 'آفر')], max_length=50)),
                ('message', models.TextField(verbose_name='message')),
                ('is_see', models.BooleanField(default=False)),
                ('is_sms', models.BooleanField(default=False)),
                ('is_send', models.BooleanField(default=False, verbose_name='is_send')),
                ('is_active', models.BooleanField(default=True, verbose_name='is_active')),
                ('time_to_send', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ('created',),
            },
        ),
    ]
