# Generated by Django 3.2 on 2022-05-10 19:40

import ckeditor.fields
from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='notification',
            managers=[
                ('default_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='notification',
            name='link',
            field=models.CharField(blank=True, max_length=240, null=True, verbose_name='link'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_see',
            field=models.BooleanField(default=False, verbose_name='is see'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_sms',
            field=models.BooleanField(default=False, verbose_name='is sms'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=ckeditor.fields.RichTextField(verbose_name='message'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='time_to_send',
            field=models.DateTimeField(blank=True, null=True, verbose_name='time to send'),
        ),
    ]
