# Generated by Django 3.2 on 2022-05-11 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_auto_20220510_1940'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ('-created',), 'verbose_name': 'Notification', 'verbose_name_plural': 'Notifications'},
        ),
        migrations.AddField(
            model_name='notification',
            name='expire_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='expire time'),
        ),
    ]
