# Generated by Django 3.2 on 2022-05-18 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_auto_20220511_0231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is active'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_send',
            field=models.BooleanField(default=False, verbose_name='is send'),
        ),
    ]
