# Generated by Django 3.2 on 2022-05-29 18:02

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post',
            managers=[
                ('default_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='image_detail',
            field=models.ImageField(null=True, upload_to='', verbose_name='image for detail'),
        ),
    ]
