# Generated by Django 3.2 on 2022-05-29 20:00

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20220529_1823'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='postcomment',
            managers=[
                ('default_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
