# Generated by Django 3.2 on 2022-06-06 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_postcomment_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='meta_description',
            field=models.CharField(default='test description', max_length=200, verbose_name='meta description'),
            preserve_default=False,
        ),
    ]
