# Generated by Django 3.2 on 2022-05-08 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_auto_20220508_2245'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BoxProduct',
        ),
    ]
