# Generated by Django 3.2 on 2022-05-09 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0004_delete_boxproduct'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-created',), 'verbose_name': 'product', 'verbose_name_plural': 'products'},
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='category.jpg', upload_to='', verbose_name='image'),
        ),
    ]
