# Generated by Django 3.2 on 2022-05-11 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0005_auto_20220509_0347'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcomment',
            options={'ordering': ('-created',), 'verbose_name': 'product comment', 'verbose_name_plural': 'product comments'},
        ),
    ]
