# Generated by Django 3.2 on 2022-05-12 00:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalogue', '0006_alter_productcomment_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=18, verbose_name='code')),
                ('discount', models.PositiveSmallIntegerField(verbose_name='discount')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('expire_time', models.DateTimeField(verbose_name='expire time')),
                ('is_limit', models.BooleanField(default=False, verbose_name='is have limit')),
                ('time_use', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='time for use')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('is_private', models.BooleanField(default=False, verbose_name='is private')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Discount',
                'verbose_name_plural': 'Discounts',
                'ordering': ('-expire_time',),
            },
        ),
    ]
