# Generated by Django 3.2 on 2022-05-12 01:41

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0007_discount'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='discount',
            managers=[
                ('default_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='discount',
            name='code',
            field=models.CharField(max_length=18, unique=True, verbose_name='code'),
        ),
    ]
