# Generated by Django 3.2 on 2022-06-06 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0008_auto_20220512_0141'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='meta_description',
            field=models.CharField(default='test description', max_length=200, verbose_name='meta description'),
            preserve_default=False,
        ),
    ]
