# Generated by Django 3.2 on 2022-05-17 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0008_auto_20220512_0141'),
        ('order', '0003_auto_20220517_0541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='product_color',
        ),
        migrations.CreateModel(
            name='OrderItemColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1, verbose_name='quantity')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_colors', to='order.orderitem', verbose_name='order oitem')),
                ('product_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='catalogue.productcolor', verbose_name='product color')),
            ],
            options={
                'verbose_name': 'order item color',
                'verbose_name_plural': 'order item colors',
            },
        ),
    ]
