# Generated by Django 3.2 on 2022-05-17 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20220517_0556'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='need_checkout',
            field=models.BooleanField(default=False, verbose_name='need checkout'),
        ),
    ]
